project:
  type: book
  output-dir: docs
execute:
  freeze: auto

book:
  title: "iskr2026"
  chapters:
      - index.qmd
      - about.qmd
      - abstract.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    number-depth: 2
